### ISSUE TITLE
source packages should be marked as developmentDependency

### ISSUE THREAD

**Issue by SurajGupta** [morelinq/srcpkg#1]
The source packages should be marked as a developmentDependency. If not, then consumers of a package that dependent on the source package will have to install the source packages, despite that code already being compiled-into the dependency.

please see developmentDependency here:
https://docs.nuget.org/ndocs/schema/nuspec

**Comment by atifaziz** [comment]
Thanks for migrating the issue. 👍

Is this something you'd like or have the time to help with via a PR?

**Comment by SurajGupta** [comment]
no problem!  let me take a crack at it...

**Comment by SurajGupta** [comment]
submitted: https://github.com/morelinq/srcpkg/pull/2
